# Generated by Django 4.1.7 on 2023-04-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_remove_cafe_business_hours_cafe_business_hours_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='latitude',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='longitude',
            field=models.CharField(max_length=255),
        ),
    ]
